# Generated by Django 4.1.3 on 2022-11-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('peso', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refrigeradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('peso', models.CharField(max_length=50)),
                ('temperatura_minima', models.CharField(max_length=50)),
                ('pantalla_inteligente', models.CharField(max_length=50)),
                ('volumen', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
