# Generated by Django 4.1.3 on 2022-12-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libros',
            new_name='Books',
        ),
    ]
